name: Secretos
run-name: Probando Secrets
on:
  push:
    branches:
      - main
jobs:
  mostrando_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: se_muestran_secretos?
        run: echo veamos si se muestra, ${{secrets.CONTRASENA}}
