name: Variables desde UI y con env
run-name: probando Variables
on:
  push:
    branches:
      - main
env:
  saludo_autor: "Hola amigo: ${{github.actor}}" #concat text like this
jobs:
  testing_vars:
    runs-on: ubuntu-latest
    steps:
      - name: var_desde_env
        run: echo $saludo_autor
      - name: var_desde_UI
        run: echo "esto es una prueaba ${{vars.PRUEBA}}"
